"""init

Revision ID: ae8bf8e6b2ce
Revises:
Create Date: 2025-07-13 14:10:34.005166

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ae8bf8e6b2ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'dashboard_summary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('views', sa.String(length=50), nullable=False),
        sa.Column('views_change', sa.String(length=50), nullable=False),
        sa.Column('views_type', sa.String(length=10), nullable=False),
        sa.Column('visits', sa.String(length=50), nullable=False),
        sa.Column('visits_change', sa.String(length=50), nullable=False),
        sa.Column('visits_type', sa.String(length=10), nullable=False),
        sa.Column('new_users', sa.String(length=50), nullable=False),
        sa.Column('new_users_change', sa.String(length=50), nullable=False),
        sa.Column('new_users_type', sa.String(length=10), nullable=False),
        sa.Column('active_users', sa.String(length=50), nullable=False),
        sa.Column('active_users_change', sa.String(length=50), nullable=False),
        sa.Column('active_users_type', sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=True),
        sa.Column('google_id', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table(
        'metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('device', sa.String(length=50), nullable=True),
        sa.Column('location', sa.String(length=50), nullable=True),
        sa.Column('value', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_metrics_device'), 'metrics', ['device'], unique=False)
    op.create_index(
        op.f('ix_metrics_event_type'), 'metrics', ['event_type'], unique=False
    )
    op.create_index(op.f('ix_metrics_location'), 'metrics', ['location'], unique=False)
    op.create_index(
        op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False
    )
    op.create_index(op.f('ix_metrics_user_id'), 'metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_user_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_location'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_event_type'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_device'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('dashboard_summary')
    # ### end Alembic commands ###
